# Generated by Django 4.1 on 2022-08-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_code", models.CharField(max_length=10, verbose_name="ユーザコード")),
                ("user_name", models.CharField(max_length=50, verbose_name="ユーザ名称")),
                ("login_time", models.DateField(verbose_name="ログイン日時")),
            ],
        ),
    ]
